env:
  APISIX_IMAGE_NAME: ${{ github.repository }}-apisix

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  build-apisix:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: retrieve Amazon TLS cert
        run: wget https://www.amazontrust.com/repository/AmazonRootCA1.pem -O docker/AmazonRootCA1.pem

      #Build apisix image
      - name: Extract metadata (tags, labels) for apisix Docker image
        id: meta-apisix
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ vars.REGISTRY }}/${{ env.APISIX_IMAGE_NAME }}
          tags: |
            type=schedule
            type=raw,value=${{ github.base_ref }}
            type=ref,event=tag
            type=raw,value=pr-${{ github.event.pull_request.number}}

      - name: Build and push apisix Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker/Dockerfile_apisix
          push: true
          tags: ${{ steps.meta-apisix.outputs.tags }}
          labels: ${{ steps.meta-apisix.outputs.labels }}

      # #Build etcd image
      # - name: Extract metadata (tags, labels) for etcd Docker image
      #   id: meta-etcd
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ vars.REGISTRY}}/${{ env.ETCD_IMAGE_NAME }}
      #     tags: |
      #       type=schedule
      #       type=raw,value=${{ github.base_ref }}
      #       type=ref,event=tag
      #       type=raw,value=pr-${{ github.event.pull_request.number}}

      # - name: Build and push etcd Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     file: docker/Dockerfile_etcd
      #     push: true
      #     tags: ${{ steps.meta-etcd.outputs.tags }}
      #     labels: ${{ steps.meta-etcd.outputs.labels }}

      # #Build apisix-gui
      # - name: Extract metadata (tags, labels) for apisix gui Docker image
      #   id: meta-gui
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ vars.REGISTRY}}/${{ env.APISIX_GUI_IMAGE_NAME }}
      #     tags: |
      #       type=schedule
      #       type=raw,value=${{ github.base_ref }}
      #       type=ref,event=tag
      #       type=raw,value=pr-${{ github.event.pull_request.number}}

      # - name: Build and push apisix gui Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     file: docker/Dockerfile_apisix_gui
      #     push: true
      #     tags: ${{ steps.meta-gui.outputs.tags }}
      #     labels: ${{ steps.meta-gui.outputs.labels }}