# This is a basic workflow to help you get started with Actions

name: Build Client

env:
  IMAGE_NAME: ${{ github.repository }}-client
  WEBADE_JCRS_URL: ${{ secrets.WEBADE_JCRS_URL }}
  NPMRC: ${{ secrets.NPMRC }}

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      TARGET_ENV:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Add .npmrc file
        run: echo -e $NPMRC > ~/.npmrc
        
      - name: Add self-referential URL
        run: sed -i 's/#{wfnews.url}/https:\/\/wfnews-client.pp93w9-${{ inputs.TARGET_ENV }}.nimbus.cloud.gov.bc.ca/' client/wfnews-war/src/main/resources/static.properties
          
      - name: Build with Maven
        run: mvn --settings server/mvn_settings/settings.xml --batch-mode --update-snapshots -f client/pom.xml -Drepo.login=${{ secrets.IDIR_AS_EMAIL }} -Drepo.password=${{ secrets.IDIR_PASSWORD }} -DskipTests package
        
      - name: Copy files to neccessary folders
        run: mkdir staging && cp client/wfnews-war/target/*.war staging
      
      - uses: actions/upload-artifact@v3
        with:
         name: Package-client
         path: staging
         
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: staging
          key: ${{ runner.os }}-maven-${{ hashFiles('**war.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
         
  docker:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: Package-client
          path: .
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.event.pull_request.number > 0 }}
        id: meta_pr
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ inputs.REGISTRY}}/${{ env.IMAGE_NAME }}-${{ github.event.pull_request.number}}
      
      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.event.pull_request.number == '' }}
        id: meta_nopr
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ inputs.REGISTRY}}/${{ env.IMAGE_NAME }}

        
      - name: Build and push Docker image (no PR)
        if: ${{ github.event.pull_request.number == '' }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta_nopr.outputs.tags }}
          labels: ${{ steps.meta_nopr.outputs.labels }}
          
      - name: Build and push Docker image (with PR)
        if: ${{ github.event.pull_request.number > 0 }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta_pr.outputs.tags }}
          labels: ${{ steps.meta_pr.outputs.labels }}
     
